package com.nutrijap.v9;

import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;

public class NutriGameView extends View{
 final MainActivity a; final Paint p=new Paint(3); final Paint stroke=new Paint(3); final SharedPreferences prefs; final Random rnd=new Random(); final float d;
 int W,H,bottom=0,page=0,ch=0,state=0,prev=-1,mission=0,xp=0,doneCount=0; long now,trans,speakUntil,dialogueAt; String dialogue=""; float px,py,tx,ty,dx,dy; boolean drag;
 final boolean[] done=new boolean[4], shopDone=new boolean[6]; final Map<Integer,Bitmap> cache=new HashMap<>(); final ArrayList<Particle> particles=new ArrayList<>();
 final RectF portrait=new RectF(),action=new RectF(),voice=new RectF(),nav0=new RectF(),nav1=new RectF(),nav2=new RectF(); final RectF[] people={new RectF(),new RectF(),new RectF(),new RectF()}, shop={new RectF(),new RectF(),new RectF(),new RectF(),new RectF(),new RectF()};
 static final int BG=Color.rgb(2,5,11),WHITE=Color.rgb(245,250,255),MUTED=Color.rgb(126,156,180),LINE=Color.rgb(24,58,84),GOOD=Color.rgb(75,226,157);
 final C[] cs={
  new C("REI","FITNESS COACH",Color.rgb(49,173,255),R.drawable.rei_sprite,true,new String[]{"CHEERFUL","STRICT","TRIUMPHANT","RELAXED"},new String[]{"בוקר טוב. אני כבר מוכנה. אתה?","תישאר איתי. משימה אחת בכל פעם.","ככה אני אוהבת לראות אותך. ביצוע, לא תירוצים.","שתי שניות מנוחה ואז ממשיכים."}),
  new C("AKARI","PRIVATE CHEF",Color.rgb(232,145,77),R.drawable.akari_sprite,true,new String[]{"JOYFUL","PLAYFUL","ANNOYED","FOCUSED"},new String[]{"הארוחה שלך מוכנה. פשוט אוכל טוב.","אתה מנסה להסיח אותי מהמטבח? כמעט הצלחת.","אל תגיד לי שדילגת על הארוחה.","עכשיו אוכלים. אחר כך ממשיכים."}),
  new C("ELENA","NUTRITION GUIDE",Color.rgb(221,190,126),R.drawable.elena,false,new String[]{"REASSURING","ANALYTICAL","DISAPPROVING","APPROVING"},new String[]{"אני שומרת על התמונה הגדולה.","עקביות מנצחת יום מושלם אחד.","זה לא חלק מהתוכנית. מתקנים וחוזרים.","יפה. השבוע מתחיל להיראות כמו מערכת שעובדת."}),
  new C("MIA","LIFESTYLE / SUPPLY",Color.rgb(255,78,162),R.drawable.mia,false,new String[]{"EXCITED","PLAYFUL","ANNOYED","CHEERFUL"},new String[]{"Supply run. נכנסים, לוקחים ויוצאים.","עוד משהו לעגלה? רק אם הוא בתוכנית.","לא קונים שטויות כי היינו רעבים בסופר.","סיימנו. מקרר מסודר, שבוע מסודר."})};
 String[][] week={{"יוגורט יווני + ½ בננה + אוכמניות","חזה עוף + סלט","3 ביצים + תרד"},{"יוגורט יווני + ½ בננה + אוכמניות","חזה עוף + סלט","3 ביצים + תרד"},{"קוטג׳ 3% + ½ בננה + אוכמניות","חזה הודו + סלט","3 ביצים קשות + קוטג׳"},{"יוגורט יווני + ½ בננה + אוכמניות","חזה עוף + סלט","3 ביצים + תרד"},{"יוגורט יווני + ½ בננה + אוכמניות","דג בתנור + סלט","3 ביצים + תרד"},{"קוטג׳ 3% + ½ בננה + אוכמניות","חזה עוף + סלט","3 ביצים קשות + קוטג׳"},{"יוגורט יווני + ½ בננה + אוכמניות","טונה + תרד + סלט","3 ביצים + תרד"}};
 String[] days={"ראשון","שני","שלישי","רביעי","חמישי","שישי","שבת"}; String[] supplies={"חלבון · עוף + הודו + דג + טונה","ביצים וחלב · 21 ביצים + יוגורט + קוטג׳","פירות · בננות + אוכמניות","ירוקים · חסה + מלפפונים + תרד","בסיס · לימונים + שמן זית","Performance · קריאטין"};
 M[] ms;
 public NutriGameView(Context c){super(c);a=(MainActivity)c;d=getResources().getDisplayMetrics().density;prefs=c.getSharedPreferences("nutri_v9",0);setLayerType(View.LAYER_TYPE_HARDWARE,null);load();say(cs[ch].lines[0],false);}
 void load(){int day=Calendar.getInstance().get(Calendar.DAY_OF_WEEK)-1;String[] w=week[day];ms=new M[]{new M("MISSION 01 · BREAKFAST",w[0],"פתיחה נקייה · בלי עומס",0),new M("MISSION 02 · MAIN MEAL",w[1],"הארוחה המרכזית של היום",1),new M("MISSION 03 · CREATINE","5g קריאטין","אחרי הארוחה המרכזית",0),new M("MISSION 04 · NIGHT",w[2],"סגירה פשוטה של היום",0)};int mask=prefs.getInt("mask",0);xp=prefs.getInt("xp",0);for(int i=0;i<4;i++){done[i]=(mask&(1<<i))!=0;if(done[i])doneCount++;}mission=first();ch=ms[mission].owner;state=done[mission]?2:1;}
 int first(){for(int i=0;i<4;i++)if(!done[i])return i;return 3;} public void setBottomOverlayInset(int v){bottom=v;}
 @Override protected void onDraw(Canvas c){now=System.currentTimeMillis();W=getWidth();H=getHeight();px+=(tx-px)*.09f;py+=(ty-py)*.09f;bg(c);top(c);if(page==0)command(c);else if(page==1)strategy(c);else supply(c);nav(c);particles(c);postInvalidateOnAnimation();}
 void bg(Canvas c){c.drawColor(BG);p.setShader(new RadialGradient(W*.3f,H*.3f,W*.75f,alpha(cs[ch].color,50),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawRect(0,0,W,H,p);p.setShader(null);p.setColor(Color.argb(20,80,180,255));for(int x=0;x<W;x+=dp(44))c.drawLine(x,0,x,H,p);for(int y=0;y<H;y+=dp(44))c.drawLine(0,y,W,y,p);}
 void top(Canvas c){t(c,"NUTRI",dp(18),dp(30),dp(23),WHITE,true,Paint.Align.LEFT);t(c,"LEVEL "+(1+xp/500)+" · "+xp+" XP",W-dp(18),dp(27),dp(10),MUTED,true,Paint.Align.RIGHT);}
 void squad(Canvas c,float y){float gap=dp(7),w=(W-dp(36)-gap*3)/4f,x=dp(18);for(int i=0;i<4;i++){RectF r=people[i];r.set(x,y,x+w,y+dp(45));p.setColor(i==ch?alpha(cs[i].color,55):Color.rgb(7,18,31));rr(c,r,dp(13),p);outline(c,r,i==ch?alpha(cs[i].color,170):LINE,dp(13));p.setColor(cs[i].color);c.drawCircle(r.left+dp(14),r.centerY(),dp(4),p);t(c,cs[i].name,r.left+dp(24),r.centerY()+dp(4),dp(10),WHITE,true,Paint.Align.LEFT);x+=w+gap;}}
 void command(Canvas c){squad(c,dp(52));float pt=dp(108),pb=Math.min(H-bottom-dp(318),pt+dp(410));if(pb<pt+dp(245))pb=pt+dp(245);portrait.set(dp(14),pt,W-dp(14),pb);portrait(c,portrait,ch,state);M m=ms[mission];float y=pb+dp(12);t(c,m.label,W-dp(18),y+dp(10),dp(9),cs[m.owner].color,true,Paint.Align.RIGHT);t(c,m.food,W-dp(18),y+dp(39),dp(22),WHITE,true,Paint.Align.RIGHT);t(c,m.meta,W-dp(18),y+dp(60),dp(10),MUTED,false,Paint.Align.RIGHT);float by=y+dp(74);p.setColor(Color.rgb(8,24,39));bar(c,dp(18),by,W-dp(18),by+dp(6),p);p.setColor(cs[ch].color);bar(c,dp(18),by,dp(18)+(W-dp(36))*doneCount/4f,by+dp(6),p);t(c,"MOMENTUM "+doneCount+" / 4",W-dp(18),by-dp(6),dp(9),MUTED,true,Paint.Align.RIGHT);action.set(dp(18),by+dp(18),W-dp(100),by+dp(65));voice.set(W-dp(92),by+dp(18),W-dp(18),by+dp(65));p.setShader(new LinearGradient(action.left,0,action.right,0,Color.rgb(13,105,242),Color.rgb(35,190,255),Shader.TileMode.CLAMP));rr(c,action,dp(14),p);p.setShader(null);t(c,done[mission]?"✓ בוצע":"סיימתי את המשימה",action.centerX(),action.centerY()+dp(4),dp(12),WHITE,true,Paint.Align.CENTER);p.setColor(Color.rgb(9,27,45));rr(c,voice,dp(14),p);t(c,"VOICE",voice.centerX(),voice.centerY()+dp(3),dp(9),cs[ch].color,true,Paint.Align.CENTER);dialogue(c,action.bottom+dp(9),H-bottom-dp(73));}
 void portrait(Canvas c,RectF r,int who,int st){C q=cs[who];p.setColor(Color.rgb(7,18,32));rr(c,r,dp(24),p);outline(c,r,alpha(q.color,90),dp(24));c.save();Path clip=new Path();clip.addRoundRect(r,dp(24),dp(24),Path.Direction.CW);c.clipPath(clip);float breathing=(float)Math.sin(now/850.0)*.007f+(now<speakUntil?(float)Math.sin(now/95.0)*.004f:0),scale=1.09f+breathing;float tr=Math.min(1,(now-trans)/280f);if(prev>=0&&tr<1)pic(c,bmp(q.res),q.sheet?prev:0,q.sheet,r,scale,px,py,(int)(255*(1-tr)));pic(c,bmp(q.res),q.sheet?st:0,q.sheet,r,scale,px,py,(int)(255*Math.max(.05,tr)));p.setShader(new LinearGradient(0,r.top,0,r.bottom,Color.TRANSPARENT,Color.argb(225,2,7,14),Shader.TileMode.CLAMP));c.drawRect(r,p);p.setShader(null);c.restore();t(c,q.name,r.left+dp(16),r.bottom-dp(40),dp(32),WHITE,true,Paint.Align.LEFT);t(c,q.role,r.left+dp(17),r.bottom-dp(22),dp(8),q.color,true,Paint.Align.LEFT);t(c,q.states[st],r.right-dp(17),r.top+dp(28),dp(9),q.color,true,Paint.Align.RIGHT);}
 void pic(Canvas c,Bitmap b,int st,boolean sheet,RectF r,float s,float x,float y,int al){if(b==null)return;int tw=sheet?b.getWidth()/4:b.getWidth(),th=b.getHeight();Rect src=new Rect(sheet?st*tw:0,0,sheet?(st+1)*tw:b.getWidth(),th);float asp=(float)tw/th,dw=r.width()*s,dh=dw/asp;if(dh<r.height()*s){dh=r.height()*s;dw=dh*asp;}RectF dst=new RectF(r.centerX()-dw/2+x,r.centerY()-dh/2+y,r.centerX()+dw/2+x,r.centerY()+dh/2+y);p.setAlpha(al);c.drawBitmap(b,src,dst,p);p.setAlpha(255);}
 void dialogue(Canvas c,float y,float b){if(b<y+dp(45))return;RectF r=new RectF(dp(14),y,W-dp(14),b);p.setColor(Color.argb(235,5,16,29));rr(c,r,dp(17),p);outline(c,r,alpha(cs[ch].color,70),dp(17));t(c,cs[ch].name,dp(26),y+dp(21),dp(10),cs[ch].color,true,Paint.Align.LEFT);int n=(int)Math.min(dialogue.length(),Math.max(0,(now-dialogueAt)/22));wrap(c,dialogue.substring(0,n),W-dp(26),y+dp(44),W-dp(52),dp(17),dp(12),WHITE);}
 void strategy(Canvas c){ch=2;squad(c,dp(52));RectF r=new RectF(dp(14),dp(108),W-dp(14),dp(335));portrait(c,r,2,state);float y=r.bottom+dp(10);t(c,"ELENA · WEEK STRATEGY",W-dp(18),y+dp(12),dp(9),cs[2].color,true,Paint.Align.RIGHT);int today=Calendar.getInstance().get(Calendar.DAY_OF_WEEK)-1;y+=dp(24);for(int i=0;i<7&&y<H-bottom-dp(88);i++){RectF q=new RectF(dp(14),y,W-dp(14),y+dp(46));p.setColor(i==today?Color.rgb(18,31,44):Color.rgb(6,17,29));rr(c,q,dp(12),p);if(i==today)outline(c,q,alpha(cs[2].color,130),dp(12));t(c,days[i]+(i==today?" · היום":""),W-dp(25),y+dp(16),dp(10),i==today?cs[2].color:WHITE,true,Paint.Align.RIGHT);t(c,week[i][1],W-dp(25),y+dp(33),dp(9),MUTED,false,Paint.Align.RIGHT);y+=dp(50);}}
 void supply(Canvas c){ch=3;squad(c,dp(52));RectF r=new RectF(dp(14),dp(108),W-dp(14),dp(320));portrait(c,r,3,state);float y=r.bottom+dp(10);int n=0;for(boolean v:shopDone)if(v)n++;t(c,"MIA · SUPPLY RUN",dp(18),y+dp(12),dp(9),cs[3].color,true,Paint.Align.LEFT);t(c,n+" / 6",W-dp(18),y+dp(12),dp(9),MUTED,true,Paint.Align.RIGHT);y+=dp(24);for(int i=0;i<6;i++){RectF q=shop[i];q.set(dp(14),y,W-dp(14),y+dp(48));p.setColor(shopDone[i]?Color.rgb(7,30,27):Color.rgb(6,17,30));rr(c,q,dp(12),p);outline(c,q,shopDone[i]?alpha(GOOD,100):LINE,dp(12));t(c,supplies[i],q.right-dp(42),q.centerY()+dp(4),dp(10),shopDone[i]?Color.rgb(150,210,180):WHITE,true,Paint.Align.RIGHT);p.setColor(shopDone[i]?GOOD:Color.rgb(14,38,57));c.drawCircle(q.right-dp(20),q.centerY(),dp(10),p);if(shopDone[i])t(c,"✓",q.right-dp(20),q.centerY()+dp(4),dp(10),BG,true,Paint.Align.CENTER);y+=dp(52);} }
 void nav(Canvas c){float b=H-bottom-dp(8),y=b-dp(55),g=dp(6),w=(W-dp(24)-2*g)/3f;nav0.set(dp(12),y,dp(12)+w,b);nav1.set(nav0.right+g,y,nav0.right+g+w,b);nav2.set(nav1.right+g,y,W-dp(12),b);navItem(c,nav0,"COMMAND",page==0,0);navItem(c,nav1,"STRATEGY",page==1,2);navItem(c,nav2,"SUPPLY",page==2,3);}
 void navItem(Canvas c,RectF r,String s,boolean on,int co){p.setColor(on?alpha(cs[co].color,55):Color.rgb(4,13,24));rr(c,r,dp(16),p);outline(c,r,on?alpha(cs[co].color,140):LINE,dp(16));t(c,s,r.centerX(),r.centerY()+dp(4),dp(9),on?WHITE:MUTED,true,Paint.Align.CENTER);}
 @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==0){dx=x;dy=y;drag=portrait.contains(x,y);return true;}if(e.getAction()==2){if(drag){tx=clamp((x-portrait.centerX())*.035f,-dp(10),dp(10));ty=clamp((y-portrait.centerY())*.025f,-dp(8),dp(8));}return true;}if(e.getAction()==1){boolean tap=Math.hypot(x-dx,y-dy)<dp(14);drag=false;tx=ty=0;if(!tap)return true;for(int i=0;i<4;i++)if(people[i].contains(x,y)){select(i);return true;}if(nav0.contains(x,y)){page=0;ch=ms[mission].owner;a.updateChatHint(cs[ch].name);say("חזרנו למשימה. "+ms[mission].food,false);return true;}if(nav1.contains(x,y)){page=1;select(2);say(cs[2].lines[1],true);return true;}if(nav2.contains(x,y)){page=2;select(3);say(cs[3].lines[0],true);return true;}if(portrait.contains(x,y)){react();return true;}if(page==0&&action.contains(x,y)){complete();return true;}if(page==0&&voice.contains(x,y)){a.speak(dialogue);return true;}if(page==2)for(int i=0;i<6;i++)if(shop[i].contains(x,y)){shopDone[i]=!shopDone[i];change(shopDone[i]?1:2);say(shopDone[i]?"סומן. ממשיכים.":"החזרנו אותו לרשימה.",false);return true;}}return true;}
 void select(int i){ch=i;state=0;prev=-1;a.updateChatHint(cs[i].name);say(cs[i].lines[0],false);} void react(){int n=(state+1)%4;change(n);say(cs[ch].lines[n],true);}
 void complete(){if(done[mission]){say("המשימה הזאת כבר סגורה.",true);return;}done[mission]=true;doneCount++;xp+=100;int mask=0;for(int i=0;i<4;i++)if(done[i])mask|=1<<i;prefs.edit().putInt("mask",mask).putInt("xp",xp).apply();change(2);say(ch==1?"יפה. הארוחה המרכזית נסגרה כמו שצריך.":"בוצע. בדיוק ככה בונים יום יציב.",true);burst(action.centerX(),action.centerY(),cs[ch].color);if(doneCount<4){mission=first();ch=ms[mission].owner;a.updateChatHint(cs[ch].name);}else{ch=0;change(2);say("ארבע מארבע. היום הזה סגור.",true);}}
 public void userMessage(String raw){String s=raw.trim();if(s.contains("סיימתי")){complete();return;}if(s.contains("קניות")||s.contains("סופר")){page=2;select(3);say("מעבירה אותך ל־Supply Run.",true);}else if(s.contains("תוכנית")||s.contains("שבוע")){page=1;select(2);say("אני פותחת את אסטרטגיית השבוע.",true);}else if(s.contains("אוכל")||s.contains("עכשיו")){page=0;ch=ms[mission].owner;a.updateChatHint(cs[ch].name);change(1);say("עכשיו: "+ms[mission].food+". "+ms[mission].meta,true);}else if(s.contains("אין לי כוח")||s.contains("עייף")){ch=0;change(1);say("לא צריך כוח לכל היום. צריך כוח למשימה אחת.",true);}else if(s.contains("קריאטין")){ch=0;change(3);say("5 גרם אחרי הארוחה המרכזית. פשוט וקבוע.",true);}else if(s.contains("רעב")){ch=2;change(0);say("לפני שמאלתרים, בודקים איפה אתה בשרשרת היום.",true);}else react();}
 public void onSpeechStarted(String s){speakUntil=System.currentTimeMillis()+Math.max(1100,s.length()*48L);} void say(String s,boolean speak){dialogue=s;dialogueAt=System.currentTimeMillis();if(speak)a.speak(s);} void change(int n){if(n==state)return;prev=state;state=Math.max(0,Math.min(3,n));trans=System.currentTimeMillis();}
 Bitmap bmp(int id){Bitmap b=cache.get(id);if(b==null){b=BitmapFactory.decodeResource(getResources(),id);cache.put(id,b);}return b;} void burst(float x,float y,int color){for(int i=0;i<25;i++){double an=rnd.nextDouble()*Math.PI*2;float sp=dp(1)+(float)rnd.nextDouble()*dp(4);particles.add(new Particle(x,y,(float)Math.cos(an)*sp,(float)Math.sin(an)*sp-dp(1),now,color));}}
 void particles(Canvas c){for(int i=particles.size()-1;i>=0;i--){Particle q=particles.get(i);float age=(now-q.birth)/850f;if(age>=1){particles.remove(i);continue;}q.x+=q.vx;q.y+=q.vy;q.vy+=.025f*d;p.setColor(alpha(q.color,(int)(255*(1-age))));c.drawCircle(q.x,q.y,dp(2),p);}}
 void t(Canvas c,String s,float x,float y,float z,int col,boolean bold,Paint.Align al){p.setShader(null);p.setColor(col);p.setTextSize(z);p.setTextAlign(al);p.setTypeface(bold?Typeface.create(Typeface.DEFAULT,1):Typeface.DEFAULT);p.setAlpha(255);c.drawText(s,x,y,p);} void wrap(Canvas c,String s,float right,float y,float max,float lh,float z,int col){p.setTextSize(z);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.RIGHT);p.setColor(col);String line="";for(String w:s.split(" ")){String q=line.isEmpty()?w:line+" "+w;if(p.measureText(q)>max&&!line.isEmpty()){c.drawText(line,right,y,p);y+=lh;line=w;}else line=q;}if(!line.isEmpty())c.drawText(line,right,y,p);} void rr(Canvas c,RectF r,float rad,Paint q){c.drawRoundRect(r,rad,rad,q);} void bar(Canvas c,float l,float t,float r,float b,Paint q){c.drawRoundRect(l,t,r,b,dp(5),dp(5),q);} void outline(Canvas c,RectF r,int col,float rad){stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeWidth(dp(1));stroke.setColor(col);c.drawRoundRect(r,rad,rad,stroke);stroke.setStyle(Paint.Style.FILL);} int alpha(int col,int a){return Color.argb(Math.max(0,Math.min(255,a)),Color.red(col),Color.green(col),Color.blue(col));} float dp(float v){return v*d;} float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
 static class C{String name,role;int color,res;boolean sheet;String[] states,lines;C(String n,String r,int c,int re,boolean sh,String[] st,String[] li){name=n;role=r;color=c;res=re;sheet=sh;states=st;lines=li;}} static class M{String label,food,meta;int owner;M(String l,String f,String m,int o){label=l;food=f;meta=m;owner=o;}} static class Particle{float x,y,vx,vy;long birth;int color;Particle(float a,float b,float c,float d,long e,int f){x=a;y=b;vx=c;vy=d;birth=e;color=f;}}
}
